# Generated by Django 2.0.3 on 2020-05-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200531_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('lg', 'Large'), ('os', 'One Size')], default='os', max_length=2),
        ),
    ]
