# Generated by Django 2.0.3 on 2020-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='topping_no',
            field=models.IntegerField(default=0),
        ),
    ]
