# Generated by Django 2.0.3 on 2020-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
