# Generated by Django 2.0.3 on 2020-06-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='is_order',
            new_name='ordered',
        ),
    ]
