# Generated by Django 2.0.3 on 2020-06-09 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_addon',
            field=models.BooleanField(default=False),
        ),
    ]
