# Generated by Django 2.0.3 on 2020-06-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200609_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.ManyToManyField(related_name='addons', to='orders.ProductVariant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.ProductVariant'),
        ),
    ]
